#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum cp0_init_step {
    CP0_INIT_STEP_ENV,
    CP0_INIT_STEP_EVENT,
    CP0_INIT_STEP_FILESYSTEM,
    CP0_INIT_STEP_CONFIG,
    CP0_INIT_STEP_PTY,
    CP0_INIT_STEP_DISPLAY,
    CP0_INIT_STEP_INPUT,
    CP0_INIT_STEP_RPC,
    CP0_INIT_STEP_AUDIO,
    CP0_INIT_STEP_PROCESS,
    CP0_INIT_STEP_SUDO,
    CP0_INIT_STEP_OSINFO,
    CP0_INIT_STEP_SCREENSHOT,
    CP0_INIT_STEP_LORA,
    CP0_INIT_STEP_WIFI,
    CP0_INIT_STEP_BLUETOOTH,
    CP0_INIT_STEP_SETTINGS,
    CP0_INIT_STEP_BQ27220,
    CP0_INIT_STEP_IMU,
    CP0_INIT_STEP_SAVED_SETTINGS,
    CP0_INIT_STEP_BATTERY,
    CP0_INIT_STEP_CAMERA,
    CP0_INIT_STEP_SOUNDCARD,
} cp0_init_step_t;

enum {
    CP0_INIT_FEATURE_FILESYSTEM = UINT64_C(1) << 0,
    CP0_INIT_FEATURE_CONFIG = UINT64_C(1) << 1,
    CP0_INIT_FEATURE_PTY = UINT64_C(1) << 2,
    CP0_INIT_FEATURE_RPC = UINT64_C(1) << 3,
    CP0_INIT_FEATURE_AUDIO = UINT64_C(1) << 4,
    CP0_INIT_FEATURE_PROCESS = UINT64_C(1) << 5,
    CP0_INIT_FEATURE_SUDO = UINT64_C(1) << 6,
    CP0_INIT_FEATURE_OSINFO = UINT64_C(1) << 7,
    CP0_INIT_FEATURE_SCREENSHOT = UINT64_C(1) << 8,
    CP0_INIT_FEATURE_LORA = UINT64_C(1) << 9,
    CP0_INIT_FEATURE_WIFI = UINT64_C(1) << 10,
    CP0_INIT_FEATURE_BLUETOOTH = UINT64_C(1) << 11,
    CP0_INIT_FEATURE_SETTINGS = UINT64_C(1) << 12,
    CP0_INIT_FEATURE_BQ27220 = UINT64_C(1) << 13,
    CP0_INIT_FEATURE_IMU = UINT64_C(1) << 14,
    CP0_INIT_FEATURE_SAVED_SETTINGS = UINT64_C(1) << 15,
    CP0_INIT_FEATURE_BATTERY = UINT64_C(1) << 16,
    CP0_INIT_FEATURE_CAMERA = UINT64_C(1) << 17,
    CP0_INIT_FEATURE_SOUNDCARD = UINT64_C(1) << 18,
};

size_t cp0_build_init_plan(uint64_t features, cp0_init_step_t *steps, size_t capacity);

#ifdef __cplusplus
}
#endif
