// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "ui.h"
#include <stdio.h>
#include <sys/stat.h>
#include <cstdlib>
#include "lvgl/src/widgets/gif/lv_gif.h"
#include "cp0_lvgl_app.h"
#include "sample_log.h"





std::unique_ptr<zero_lvgl_os> home;
void ui_init(void)
{
    home = std::make_unique<zero_lvgl_os>();
    home->start();
}

LauncherFonts &launcher_fonts()
{
    if (!home) {
        std::abort();
    }
    return *home->fonts_;
}
