/*
 * SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
 *
 * SPDX-License-Identifier: MIT
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "ui.h"
#include "launcher_ui_app_page.hpp"
#include "ui_low_battery.h"
#include "ui_global_hint.h"
#include "ui_loading.h"
#include "ui_screensaver.h"
#include <stdio.h>
#include <cstdlib>
#include "lvgl/src/widgets/gif/lv_gif.h"
#include "cp0_lvgl_app.h"
#include "sample_log.h"

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

std::unique_ptr<LauncherUiRuntime> home;

namespace launcher_ui {

void init()
{
    if (home)
        return;
    cp0_keyboard_set_global_key_handler(ui_global_hint::on_key);
    home = std::make_unique<LauncherUiRuntime>();
    home->start();
    launcher_battery_ui::init_warning();
}

void deinit()
{
    cp0_keyboard_set_global_key_handler(nullptr);
    ui_global_hint::shutdown();
    launcher_battery_ui::shutdown_warning();
    ui_loading::shutdown();
    ui_screensaver_deinit();
    home.reset();
}

} // namespace launcher_ui
