// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "ui.h"
#include <stdio.h>
#include <sys/stat.h>
#include "lvgl/src/widgets/gif/lv_gif.h"
#include "cp0_lvgl_app.h"
#include "sample_log.h"
///////////////////// VARIABLES ////////////////////

// LVGL objects exported through ui_obj.h.
#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN
#define UI_DEFINE_OBJECT( x ) lv_obj_t * x ;
#define UI_DEFINE_EVENT_FUN(x) ;
#include "ui_obj.h"
#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN

// Launcher animation timing.
int Animation_time = 200;


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif


///////////////////// FUNCTIONS ////////////////////



char* cimg_path(const char *name)
{
    static char path_buf[512];
    snprintf(path_buf, sizeof(path_buf), "%s", cp0_file_path(name));
    return path_buf;
}

char* caudio_path(const char *name)
{
    static char path_buf[512];
    snprintf(path_buf, sizeof(path_buf), "%s", cp0_file_path(name));
    return path_buf;
}

char* cfont_path(const char *name)
{
    static char path_buf[512];
    snprintf(path_buf, sizeof(path_buf), "%s", cp0_file_path(name));
    return path_buf;
}
