def_hal_fun(void(std::string), cp0_signal_audio_play)
def_hal_fun(void(bool), cp0_signal_audio_cap)
def_hal_fun(void(std::list<std::string>, std::function<void(int, std::string)>), cp0_signal_audio_setup)
def_hal_fun(void(std::list<std::string>, std::function<void(int, std::string)>), cp0_signal_audio_api)
def_hal_fun(void(), cp0_signal_network)
def_hal_fun(void(), cp0_signal_forkexec)
def_hal_fun(void(), cp0_signal_screenshot)
def_hal_fun(void(std::function<void()>), cp0_signal_battery_pub)
def_hal_fun(void(std::list<std::string>, std::function<void(int, std::string)>), cp0_signal_camera_api)
def_hal_fun(void(std::string), cp0_signal_system_play)
